# Generated by Django 4.1.7 on 2023-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('registration_date', models.DateTimeField()),
                ('disease_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
