# Generated by Django 4.1.7 on 2023-02-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_drink_hospital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Pacient',
        ),
    ]
